apiVersion: v1
kind: PersistentVolume
metadata:
  name: fc-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: file.cache.csi.aws.com
    volumeHandle: fc-0ef97ba968aaae830
    volumeAttributes:
      dnsname: fc-0ef97ba968aaae830.fsx.us-east-1.amazonaws.com
      mountname: uvh2hbev

