apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fc-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi
  volumeName: fc-pv
